#!/usr/bin/ruby

# method dependency graph

$: << File.expand_path("../lib", __FILE__)

require "call_graph"

filename_rb = ARGV[0]
rb = File.read(filename_rb)
dot = call_graph(rb)
filename_dot = filename_rb.sub(/\.rb$/, "") + ".dot"
File.write(filename_dot, dot)
